import Head from 'next/head';
import Footer from './partials/Footer';
import NavBar from './partials/Navbar';

export default function Page({ children }) {
  return (
    <>
      <Head>
        <title>Chesky</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar />
      <main className='mx-auto px-4 lg:container'>{children}</main>
      <Footer />
    </>
  );
}
